title: Serangoon Garden Secondary School
url: https://www.sgs.moe.edu.sg
favicon: /images/School-Logo.jpg
colors:
  primary-color: "#263056"
  secondary-color: "#002fa7"
  media-colors:
    - title: media-color-one
      color: "#4056a1"
    - title: media-color-two
      color: "#4056a1"
    - title: media-color-three
      color: "#4a90e2"
    - title: media-color-four
      color: "#4a90e2"
    - title: media-color-five
      color: "#4a90e2"
description: ""
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d1c2l9q9guwj9m.amplifyapp.com
prod: https://master.d1c2l9q9guwj9m.amplifyapp.com
shareicon: /images/School-Logo.jpg
is_government: true
facebook-pixel: ""
google_analytics: ""
linkedin-insights: ""
resources_name: Resources
google_analytics_ga4: ""
